[package]
name = "atl-checker"
version = "0.1.0"
authors = ["jacob"]
edition = "2018"

[features]
default = []
graph-printer = []

[dependencies]
crossbeam-channel = "0.5.0"
num_cpus = "1.13.0"
clap = "2.33.3"
log = "0.4.11"
log4rs = "0.12.0"