name: Clippy check
on: push
jobs:
  clippy_check:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          components: clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features