name: Formatting checker
on: push
jobs:
  check-formatting:
    name: Check formatting with rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          components: rustfmt

      - name: Check formatting with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check