name: Run tests
on: push
jobs:
  test-code:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features